name: comet
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

