name: comet
description: An AI-Powered Folder Explorer
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.5.0
  cli_completion: ^0.5.0
  dotenv: ^4.2.0
  google_generative_ai: ^0.3.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.14.0
  path: ^1.9.0
dev_dependencies:
  lints: ^3.0.0
  
executables:
  comet: main



