name: comet
description: An AI-Powered Folder Explorer
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  dotenv: ^4.2.0
  google_generative_ai: ^0.2.2
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
